### ISSUE TITLE
Uso de una ruta absoluta en la creación de registros de metadatos

### ISSUE THREAD

**Issue by oscarsa** [oscarsa/catmdedit-vv#2]
En la creación de registros de metadatos , descrito en el fichero `catmdedit/repository/sources/metadata.rdf`  apunta a una ruta inexistente ( `E:/workspacesEclipse/.../repository/metadata `).

/cc @mariaarino93

**Comment by davidmavi16** [comment]
Problema de una versión anterior. Ya está resuelto
